Use time types instead of long.
This fixes the build on macOS:

Before:
```
src/itimer.cpp:57:34: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
    struct itimerval tv = {{sec, usec}, {sec, usec}};
                                 ^~~~
src/itimer.cpp:57:34: note: insert an explicit cast to silence this issue
    struct itimerval tv = {{sec, usec}, {sec, usec}};
                                 ^~~~
                                 static_cast<__darwin_suseconds_t>( )
src/itimer.cpp:57:47: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in initializer list [-Wc++11-narrowing]
    struct itimerval tv = {{sec, usec}, {sec, usec}};
                                              ^~~~
src/itimer.cpp:57:47: note: insert an explicit cast to silence this issue
    struct itimerval tv = {{sec, usec}, {sec, usec}};
                                              ^~~~
                                              static_cast<__darwin_suseconds_t>( )
2 errors generated.
```

This is because on macOS `suseconds_t` is `int`, not `long`.